server {
    listen 8080;
    server_name a;
    root /a;
    index index.html;
}

server {
    listen 127.0.0.1:9090;
    server_name b;
    root /b;
    index home.html;
    location /api {
        allowed_methods GET POST;
        autoindex off;
    }
}
