server {
    listen 0.0.0.0:8002;

    server_name localhost;

    root ./_bsugerTests/www;
    index index.html;

    autoindex off;

    client_max_body_size 200;

    location / {
        client_max_body_size 200;
    }

    location /upload {
        client_max_body_size 200;
        autoindex on;
    }

    location /test {
        allowed_methods DELETE;
        client_max_body_size 200;
    }

    location /test2 {
        allowed_methods GET POST;
        client_max_body_size 200;
    }

    location /forbidden {
        return 599 "Forbidden";
        client_max_body_size 200;
    }

    location /cgi-bin {
        client_max_body_size 200;
    }
}

server {
    listen 0.0.0.0:8003;

    server_name www.example.com;

    root ./_bsugerTests/vhosts/example;
    index index.html;

    client_max_body_size 200;

    location / {
        client_max_body_size 200;
    }
}

server {
    listen 0.0.0.0:8003;

    server_name www.42.fr;

    root ./_bsugerTests/vhosts/42fr;
    index index.html;

    client_max_body_size 200;

    location / {
        client_max_body_size 200;
    }
}
